using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;

namespace ERP
{
    public partial class frmPrimaryAccounts : DevExpress.XtraEditors.XtraForm
    {
        Presentation.CLS_Accounts acc = new Presentation.CLS_Accounts();
        public frmPrimaryAccounts()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            sqlDataSource1.Fill();
        }

        private void frmPrimaryAccounts_Load(object sender, EventArgs e)
        {
            lstAddInterfaces.DataSource = acc.Get_Interfaces();
            lstAddInterfaces.DisplayMember = "name";
            lstAddInterfaces.ValueMember = "Id";
            lstEditInterfaces.DataSource = acc.Get_Interfaces();
            lstEditInterfaces.DisplayMember = "name";
            lstEditInterfaces.ValueMember = "Id";
            lstAddInterfaces.UnCheckAll();
            lstEditInterfaces.UnCheckAll();
            //
           // dgv.DataSource = acc.Get_PrimaryAccounts();
        }

        private void btnAdd_Click(object sender, EventArgs e)
        {
            var lst = lstAddInterfaces.SelectedItems.Cast<DataRowView>();
            if (txtAddName.Text != "" && lstAddInterfaces.SelectedItems.Count > 0)
            {
                int[] interfaces = new int[lstAddInterfaces.SelectedItems.Count];
                int i = 0;
                foreach (var item in lst)
                {
                    interfaces[i++] = int.Parse(item.Row[0].ToString());
                }
                acc.Add_PrimaryAccount(txtAddName.Text, interfaces);
                txtAddName.Text = "";
                lstAddInterfaces.UnCheckAll();
                sqlDataSource1.Fill();
            }
        }

        private void dgv_Click(object sender, EventArgs e)
        {

        }
    }
}